theme = "tokyonight_storm"

[editor]
true-color = true
line-number = "relative"
end-of-line-diagnostics = "disable"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.indent-guides]
# I dislike how selections don't change the background of the guide
render = true
character = "·"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
# this is off because elixir-ls wants to always display docs for for
# def, if, defmodule and other useless things instead of helpful docs.
# display-signature-help-docs = false
auto-signature-help = false

[keys.insert]
"C-d" = ":insert-output exec $SHELL -lc 'dbg_snippet'"
"C-k" = "signature_help"

[keys.normal]
"X" = "extend_line_above"

[keys.normal.space]
"F" = "file_picker_in_current_buffer_directory"

[keys.normal.space.space]
# open location in github
"g" = ":sh exec $SHELL -lc 'gh browse %{filename:repo_rel}:%{linenumber}'"
# format selected json
"j" = ":pipe jq"
# copy the current line to the clipboard
"l" = ":sh exec $SHELL -lc 'echo -n %{filename:repo_rel}:%{linenumber} | fish_clipboard_copy'"
# send keys to rerun in named tmux test pane
"p" = ":sh exec $SHELL -lc 'rerun_tests'"
# send keys to rerun the pane to the right of the current pane
"r" = ":sh exec $SHELL -lc 'rerun_right'"
# send keys to rerun in named tmux shell pane
"s" = ":sh exec $SHELL -lc 'rerun_shell'"
# format selected xml
"x" = ":pipe xmllint --format -"
