# Elixir
[language-server.lexical]
command = "start_lexical.sh"

[language-server.elixir-ls]
command = "language_server.sh"

[[language]]
name = "elixir"
language-servers = ["elixir-ls"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "heex"
language-servers = ["elixir-ls"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

# Go
[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["go.work", "go.mod"]
auto-format = true
formatter = { command = "goimports" }
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = [ "gopls", "golangci-lint-lsp" ]
indent = { tab-width = 4, unit = "\t" }

# JSON
[[language]]
name = "json"
auto-format = true
formatter = { command = "jq", args = [".", "-"] }
indent = { tab-width = 2, unit = "  " }

# ROC
[language-server.roc-ls]
command = "roc_language_server"

[[language]]
name = "roc"
scope = "source.roc"
injection-regex = "roc"
file-types = ["roc"]
shebangs = ["roc"]
roots = []
comment-token = "#"
language-servers = ["roc-ls"]
indent = { tab-width = 4, unit = "  " }
auto-format = true
formatter = { command = "roc", args =[ "format", "--stdin", "--stdout"]}

[[grammar]]
name = "roc"
source = { git = "https://github.com/faldor20/tree-sitter-roc.git", rev = "0b1afe88161cbd81f5ddea1bb4fa786314ed49a7" }

# XML
[[language]]
name = "xml"
auto-format = true
formatter = { command = "xmllint", args = ["--format", "-"] }
indent = { tab-width = 2, unit = "  " }

# Zig
[language-server.zls]
command = "/home/robmerrell/projects/gh/zls/zig-out/bin/zls"
