set -g extended-keys on

# remap prefix to C-space
unbind C-b
set -g prefix C-Space
bind-key C-Space send-prefix

# reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# clipboard nonsense
set -g set-clipboard on
set -g allow-passthrough on

# vi copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# popup cheatsheet
unbind 'i'
bind i display-popup -h 75% 'exec $SHELL -lc "cheat_tmux"'

# tools
bind C-y display-popup -h 95% -w 95% -E -d "#{pane_current_path}" 'exec $SHELL -lc "yazi"'
bind C-l display-popup -h 95% -w 95% -E -d "#{pane_current_path}" 'exec $SHELL -lc "lazygit"'

# window
bind c new-window -a -c "#{pane_current_path}"
bind-key -n M-[ previous-window
bind-key -n M-] next-window

# pane splitting
unbind '"'
unbind %
unbind s
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# pane movement
setw -g mode-keys vi
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R

# pane sizing
bind-key H resize-pane -L 5
bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key L resize-pane -R 5

# zooming
bind-key -n M-= resize-pane -Z

# colors
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# don't pause on escape
set -s escape-time 0

# mouse support
set -g mouse on
# set -g mouse-select-pane on

# status
set-option -g status-style bg=#24273a,fg=#b7bdf8
set-option -g status-position "top"
set-option -g status-left ""
set-option -g status-right "[#S]"
set-option -g status-justify "centre"
set-option -g window-status-format "#[fg=#5b6078]• #{?window_zoomed_flag,↯,}#W#{?window_zoomed_flag,↯,}  "
set-option -g window-status-current-format "#[fg=#7dc4e4]• #{?window_zoomed_flag,↯,}#W#{?window_zoomed_flag,↯,}  "

# panes
set -g pane-active-border-style bg=default,fg=#7dc4e4
set -g pane-border-style fg=#b7bdf8

# windows
set -g window-style "bg=#24273a"
set -g window-active-style "bg=#24273a"

# plugins
# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'jaclu/tmux-menus'

# run '~/.tmux/plugins/tpm/tpm'
